server:
  port: 9191
spring:
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://localhost:3306/electronic_mall?serverTimezone=GMT%2b8
    username: root
    password: 123456
  servlet:
    multipart:
      max-file-size: 30MB
  redis:
    database: 0
    host: 127.0.0.1
    port: 6379
    lettuce:
      pool:
        min-idle: 0
        max-active: 8
        max-idle: 8
        max-wait: -1ms
    connect-timeout: 30000ms

mybatis:
  mapper-locations: classpath:mapper/*.xml
  configuration:
    map-underscore-to-camel-case: true

alipay:
  appId: 2021000148642840
  merchantPrivateKey: MIIEvAIBADANBgkqhkiG9w0BAQEFAASCBKYwggSiAgEAAoIBAQCN2UIIX5ggVpSkod0ZgyY1wE2nRmEpPPI10Zr2hc3hadlxQBgWs7tDva/3r5pZXBoUgMOd4T5cob/sjFhdgqV9m47VPHogrUlMATEHfXyCGUYYZxEuRjKVIblq4Kh862XWWiY/r7ViyxFFkMWHLJ6eCgH1x1rTfwL8OOKkzX3aP4MQsOkO58lSG0SqIArafr9ef6APizgUKCBUegMFVmFc8iwmqzNVqQvzA3x2OdJxKnHUFC7f660XEl7hfopTzXU+hMPeh8z/scLw2BqyjW4AIfezMAgwBc5kILdxDPrylxqVc3Jpilxv4BUUS2HgWGZSr3NvqdOTGJdDbwMlHbmtAgMBAAECggEAdalTZtK0w45N+knxtunc1hVP1INCsQxG9XGKkxbmciZ1IcXCtYIcwdIkltXouFr3ny44FUvziK77HmJEIjzuvUQ9tI9X1qcm9469drMWhmwkgrVrwPCloKK6xPbZi9VPQgDBXW6IjQxYpVWzI69VW0591bupkWn3tfQRvBZgYJmv2/yAXwSXgf9MTZLTekNMDo/LqpOCD3bvbpC+32rI5gwF0nW8fonAKm1+LjnnRgCVx/iqezavGRYYYd2cOQP8lFmuqLsyD+wdfkInQG8BcFW4N/e9H2ceHNyCMCFZwtjHUnS7ZN3BHTJT31CfAsUH+7YSD7KAM0uEvby1s5nswQKBgQDoeSZc+EKfsTx7yrXLmFgSwaAm2srhrI8zIQX+jVzutiW9FWrDnJX5pTj9Kyv/cNXuFzMwlsdlmQ89un76w28GfQnvgtGzbADTyegGLxDRWgAOFw2xQFmokQkQkL4a/LjMwRjnOYuNBpt2igvClup9PZNlz43b6afkfazZS+yFWQKBgQCcNDuEJquv4lVXYxGYwXvCEYUTO13sGGJoslh/7GymzAjL8HzEDbJ5QUQmr803fG1JLmygpiuuPO9tx7jsPMyGi4CF2rpQyplo8F6dugleodxKHwL7FUnGgtOK+d8lQnmCE6A4qAuqlLyAF5sqv0MU693MjiCB7vyR6leFr2oIdQKBgB8JvdN/2fVURo0InYkXR/sJGwbVA21qCpx69j/sQ9IjQ5qhN2XyjBuOsbMrhm5OdGGbe1wrZWftLZnCQp3cZgBpxV/TCYh5DQs5096vfgFVkNhQv6VAwDe/VYR+rsMPpuS/i0Gj7zve+/axq6xJVflutTVMptYLtjzNgrxoZKXRAoGACHuRq9iJxFBvQAKiRwBi3yQibOvxasvcNEFTKwdE0z4LUD/sFp2Dzq/rqoorg9LfAHVj8slzX8/xVK3e7f1TQg87WImLSq3l7Nv412nt7lSt6NyMReRfEEe0gzyUkKpufNDiB5GgqI/ROMePZp/iXbV9Ywlo3IWE88udGyZuhK0CgYA4dHKX+wuI+02SdzDkr2aJ7MXbmmwLV81PBofZC4m9DFhpmjKZXbWyLSHPlv9SHHi1DvZbMiD5ab9u7PL+MPdTQ2kr/LKQ9T9yxM3lRHyoR93k/v82zjbSRkVXnOlPvvS37+9j21L48PTTQiiPe3txN4H2vVng96BebpfSYC/kPQ==
  alipayPublicKey: MIIBIjANBgkqhkiG9w0BAQEFAAOCAQ8AMIIBCgKCAQEAjdlCCF+YIFaUpKHdGYMmNcBNp0ZhKTzyNdGa9oXN4WnZcUAYFrO7Q72v96+aWVwaFIDDneE+XKG/7IxYXYKlfZuO1Tx6IK1JTAExB318ghlGGGcRLkYylSG5auCofOtl1lomP6+1YssRRZDFhyyengoB9cda038C/DjipM192j+DELDpDufJUhtEqiAK2n6/Xn+gD4s4FCggVHoDBVZhXPIsJqszVakL8wN8djnScSpx1BQu3+utFxJe4X6KU811PoTD3ofM/7HC8Ngaso1uACH3szAIMAXOZCC3cQz68pcalXNyaYpcb+AVFEth4FhmUq9zb6nTkxiXQ28DJR25rQIDAQAB
  notifyUrl: http://www.baidu.com/notify_alipay.jsp
  returnUrl: http://member.zyz.com/memberOrder.html
  signType: RSA2
  charset: utf-8
  gatewayUrl: https://openapi-sandbox.dl.alipaydev.com/gateway.do
